# Generated by Django 3.2.5 on 2021-11-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notemodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='content',
            field=models.TextField(),
        ),
    ]
