# Generated by Django 3.2.5 on 2021-11-02 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,255}$', 'Only Alfa, min 2, max 255')])),
                ('surname', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2,255}$', 'Only Alfa, min 2, max 255')])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)])),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
