# Generated by Django 3.2.9 on 2021-11-17 20:36

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=s3direct.fields.S3DirectField(default='../../images/avatar.jpg'),
        ),
    ]
