# Generated by Django 3.2.9 on 2021-11-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_alter_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to=''),
        ),
    ]
